# Generated by Django 2.1.2 on 2018-11-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20181103_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_pick',
            new_name='user_pic',
        ),
    ]
