# Generated by Django 2.1.2 on 2018-11-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20181103_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='home_loc',
        ),
        migrations.AddField(
            model_name='person',
            name='home_building',
            field=models.CharField(db_index=True, default=1, max_length=1000, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='person',
            name='home_city',
            field=models.CharField(db_index=True, default='Минск', max_length=1000, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='person',
            name='home_country',
            field=models.CharField(choices=[('Беларусь', 'Беларусь'), ('Россия', 'Россия'), ('Украина', 'Украина')], db_index=True, default=('Беларусь', 'Беларусь'), max_length=1000, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='person',
            name='home_street',
            field=models.CharField(db_index=True, default='пр.Рокоссовского', max_length=1000, verbose_name='Улица'),
        ),
    ]
